In [1]:
import psycopg2
import nltk
import pandas as pd
import numpy as np
import re
import string
import spacy
import sklearn
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split

In [203]:
# importing and creating df (has to have type_id)

# usage: specify file location, sample size and seed(used by random)
#filepath = '../Data_sample/FakeNewsCorpus_250.csv' # 250 rows of FakeNewsCorpus
filepath = '../Data_git_ignore/1mio-raw.csv'      # 1 mil rows raw
filepath = '../Data_git_ignore/clean_corpus_25k.csv'
#s = 1000000                                      # desired sample size
#seed = 1                                         # seed used by Pseudorandom number generator

df = pd.read_csv(filepath, index_col = [0])
df["content"] = df["content"].astype(str)
# create type_id
df['type_id'] = df.groupby(['type']).ngroup()

df.head()

id               domain  type  \
1496  338715.0  theinternetpost.net  fake   
8192   30948.0    beforeitsnews.com  fake   
5154  819308.0    beforeitsnews.com  fake   
2272  339605.0  theinternetpost.net  fake   
2198   24651.0    beforeitsnews.com  fake   

                                                    url  \
1496        https://theinternetpost.net/tag/global-war/   
8192  http://beforeitsnews.com/spirit/2013/06/more-t...   
5154  http://beforeitsnews.com/international/2013/01...   
2272   https://theinternetpost.net/tag/free-trade-area/   
2198  http://beforeitsnews.com/business/2015/11/ente...   

                                                content  \
1496  we are witnessing a great turning inward in th...   
8192  more than a parade and my new manifesto of rea...   
5154  dallas gun buyback program countered with succ...   
2272  by paul j balles many industries that started ...   
2198  enterprise vsat market global research and ana...   

                      scraped_at                 inserted_at  \
1496  2018-01-25 20:13:50.426130  2018-02-02 01:19:41.756632   
8192  2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   
5154  2018-01-25 20:13:50.426130  2018-02-02 01:19:41.756632   
2272  2018-01-25 20:13:50.426130  2018-02-02 01:19:41.756632   
2198  2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   

                      updated_at  \
1496  2018-02-02 01:19:41.756664   
8192  2018-02-02 01:19:41.756664   
5154  2018-02-02 01:19:41.756664   
2272  2018-02-02 01:19:41.756664   
2198  2018-02-02 01:19:41.756664   

                                                  title           authors  \
1496                                  THE INTERNET POST               NaN   
8192           More than a parade, and my new manifesto  Lisa Beck Living   
5154  Dallas Gun Buyback Program Countered With Succ...               NaN   
2272                                  THE INTERNET POST               NaN   
2198  Enterprise VSAT Market Global Research and Ana...               NaN   

      keywords meta_keywords  \
1496       NaN           NaN   
8192       NaN           NaN   
5154       NaN           NaN   
2272       NaN           NaN   
2198       NaN           NaN   

                                       meta_description  \
1496  Posts about Global War written by ajfloyd and ...   
8192                                                NaN   
5154                                                NaN   
2272     Posts about Free trade area written by ajfloyd   
2198                                                NaN   

                                                   tags  summary  source  \
1496  global conflict, war on terror, United States,...      NaN     NaN   
8192                                                NaN      NaN     NaN   
5154                                                NaN      NaN     NaN   
2272  employment, Free trade agreement, United State...      NaN     NaN   
2198                                                NaN      NaN     NaN   

      type_id                                   content_tokenize  
1496        3  ['we', 'are', 'witnessing', 'a', 'great', 'tur...  
8192        3  ['more', 'than', 'a', 'parade', 'and', 'my', '...  
5154        3  ['dallas', 'gun', 'buyback', 'program', 'count...  
2272        3  ['by', 'paul', 'j', 'balles', 'many', 'industr...  
2198        3  ['enterprise', 'vsat', 'market', 'global', 're...

In [5]:
df.index

Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
       ...
       9924, 9925, 9926, 9927, 9928, 9929, 9930, 9931, 9932, 9933],
      dtype='object', length=1000000)

In [3]:
#1
df['id'] = pd.to_numeric(df['id'], errors = 'coerce', downcast = 'integer')
df.dropna(subset=['id'], inplace = True)
#df.drop_duplicates(subset = 'content', inplace = True)
df.drop_duplicates(subset = 'id', inplace = True)
df.id = df.id.astype(int)



In [112]:
df.loc[df['id'] == np.nan]

Empty DataFrame
Columns: [id, domain, type, url, content, scraped_at, inserted_at, updated_at, title, authors, keywords, meta_keywords, meta_description, tags, summary, source, type_id]
Index: []

In [5]:
df.loc[df['id'].duplicated()]

Empty DataFrame
Columns: [id, domain, type, url, content, scraped_at, inserted_at, updated_at, title, authors, keywords, meta_keywords, meta_description, tags, summary, source, type_id]
Index: []

In [6]:
df.reset_index(inplace = True, drop = True)
df.index.value_counts()

2047      1
983221    1
995507    1
997554    1
991409    1
         ..
717812    1
707571    1
705522    1
711665    1
0         1
Length: 999934, dtype: int64

In [36]:
#df.info()
#df.count

In [7]:
dupidx_lst = df.loc[df['content'].duplicated()].index.tolist()

In [8]:
df_Uniq = df.loc[~df.index.isin(dupidx_lst)]

In [108]:
df_Uniq.shape

(660914, 17)

In [113]:
df_Uniq.loc[df_Uniq.type_id == -1]

id                domain type  \
397         463       www.cnsnews.com  NaN   
663         751        freebeacon.com  NaN   
664         752        freebeacon.com  NaN   
3097       3569  www.greenmedinfo.com  NaN   
3098       3570  www.greenmedinfo.com  NaN   
...         ...                   ...  ...   
993691  1163797    www.emptywheel.net  NaN   
994996  1165136       www.newsmax.com  NaN   
995014  1165155       www.newsmax.com  NaN   
995132  1165273          tomwoods.com  NaN   
997307  1167488       www.cnsnews.com  NaN   

                                                      url  \
397     https://www.cnsnews.com/news/article/melanie-a...   
663     http://freebeacon.com/politics/pelosi-tries-ex...   
664     http://freebeacon.com/uncategorized/george-sor...   
3097     http://www.greenmedinfo.com/gmi-blogs/docmalerba   
3098    http://www.greenmedinfo.com/guide/health-guide...   
...                                                   ...   
993691  http://www.emptywheel.net/2013/01/25/kerry-res...   
994996  https://www.newsmax.com/Newsmax-Tv/Ramones-Mar...   
995014  https://www.newsmax.com/US/obituary-tommy-ramo...   
995132       https://tomwoods.com/the-fast-food-protests/   
997307  https://www.cnsnews.com/news/article/susan-jon...   

                                                  content  \
397     Sen. Dick Durbin (D-Ill.) (Screenshot of C-SPA...   
663     BY: Follow @susancrabtree\n\n\n\nHouse Minorit...   
664     BY: Follow @JoeSchoffstall\n\n\n\nLiberal bill...   
3097    All articles by Larry Malerba, DO\n\nThe Homeo...   
3098    The Shocking Lack of Evidence Supporting Flu V...   
...                                                   ...   
993691  At his confirmation hearing yesterday before t...   
994996  The Ramones famously sang "I Wanna Be Sedated"...   
995014  Tommy Ramone, a co-founder of the seminal punk...   
995132  Fast-food workers have begun protesting their ...   
997307  The Obamacare website, HealthCare.gov. (AP)\n\...   

                        scraped_at                 inserted_at  \
397     2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   
663     2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   
664     2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   
3097    2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   
3098    2018-01-25 16:17:44.789555  2018-02-02 01:19:41.756632   
...                            ...                         ...   
993691  2018-01-25 20:13:50.426130  2018-02-02 01:19:41.756632   
994996  2018-01-25 20:13:50.426130  2018-02-02 01:19:41.756632   
995014  2018-01-25 20:13:50.426130  2018-02-02 01:19:41.756632   
995132  2018-01-25 20:13:50.426130  2018-02-02 01:19:41.756632   
997307  2018-01-25 20:13:50.426130  2018-02-02 01:19:41.756632   

                        updated_at  \
397     2018-02-02 01:19:41.756664   
663     2018-02-02 01:19:41.756664   
664     2018-02-02 01:19:41.756664   
3097    2018-02-02 01:19:41.756664   
3098    2018-02-02 01:19:41.756664   
...                            ...   
993691  2018-02-02 01:19:41.756664   
994996  2018-02-02 01:19:41.756664   
995014  2018-02-02 01:19:41.756664   
995132  2018-02-02 01:19:41.756664   
997307  2018-02-02 01:19:41.756664   

                                                    title  \
397     Sen. Dick Durbin Calls DACA ‘The Civil Rights ...   
663     Pelosi Tries to Extend Tax Break for Two of He...   
664     George Soros Spent Record Amount Lobbying Duri...   
3097                    Recent Blogs by Larry Malerba, DO   
3098                       Health Guide: Vaccine Research   
...                                                   ...   
993691  Kerry Resists Rand Paul on Pakistan Funding Qu...   
994996  Marky Ramone: We Were Punk Brothers But Politi...   
995014      Tommy Ramone, Last of the Ramones, Dies at 65   
995132                             The Fast Food Protests   
997307  White House Tells Obamacare Subscribers to Mak...   

           

In [12]:
df_Uniq['type'].loc[df_Uniq['type'] == 'reliable'].value_counts().min()

5222

In [107]:
df_Uniq.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            999868, 999880, 999881, 999882, 999883, 999895, 999906, 999913,
            999923, 999927],
           dtype='int64', length=660914)

In [13]:
df_Uniq.content.nunique()

660914

In [12]:
#USE THIS
# This can generate a dataset with random purmutation and a max size for each type(can be smaller if desired max is not possible)

# max size for type
max_size = 7000
# traning_set ratio - splits data into traning=ratio,  test and validate=(1-ratio)/2 ex. train=80%, test=10%, validate=10%
ratio=0.8
# Labels to include - ['fake', 'satire', 'bias', 'conspiracy', 'state', 'junksci', 'hate', 'clickbait', 'unreliable', 'political', 'reliable'] - all labels
use_types = ['fake', 'satire', 'bias', 'conspiracy', 'junksci', 'hate', 'clickbait', 'unreliable', 'political', 'reliable', 'rumor']
# Random seed
rnd = 1

# initialize dataframes
train    = pd.DataFrame(columns = df_Uniq.columns)
test     = pd.DataFrame(columns = df_Uniq.columns)

# add type to test splits
for t in use_types:

    # type size
    type_size = df_Uniq['type'].loc[df_Uniq['type'] == t].value_counts().min()

    # set size of type slice
    if type_size < max_size:
        tmp = df_Uniq.loc[df_Uniq['type'] == t].sample(n = type_size, random_state=rnd)
    else:
        tmp = df_Uniq.loc[df_Uniq['type'] == t].sample(n = max_size, random_state=rnd)

    # split current type
    train_tmp, test_tmp = np.split(tmp, [int(ratio * len(tmp))])

    # add tmp to dataframes
    train    = pd.concat([train, train_tmp])
    test     = pd.concat([test, test_tmp])
    
    # print split shape
    print("=>", t, tmp.shape, train_tmp.shape, test_tmp.shape)

print("\n[Final split]\ntrain, test==>", train.shape, test.shape)

=> fake (7000, 17) (5600, 17) (1400, 17)
=> satire (7000, 17) (5600, 17) (1400, 17)
=> bias (7000, 17) (5600, 17) (1400, 17)
=> conspiracy (7000, 17) (5600, 17) (1400, 17)
=> junksci (7000, 17) (5600, 17) (1400, 17)
=> hate (3112, 17) (2489, 17) (623, 17)
=> clickbait (7000, 17) (5600, 17) (1400, 17)
=> unreliable (7000, 17) (5600, 17) (1400, 17)
=> political (7000, 17) (5600, 17) (1400, 17)
=> reliable (5222, 17) (4177, 17) (1045, 17)

[Final split]
train, test==> (51466, 17) (12868, 17)


In [13]:
pd.merge(train,test, on =['content'], how ='inner')

Empty DataFrame
Columns: [id_x, domain_x, type_x, url_x, content, scraped_at_x, inserted_at_x, updated_at_x, title_x, authors_x, keywords_x, meta_keywords_x, meta_description_x, tags_x, summary_x, source_x, type_id_x, id_y, domain_y, type_y, url_y, scraped_at_y, inserted_at_y, updated_at_y, title_y, authors_y, keywords_y, meta_keywords_y, meta_description_y, tags_y, summary_y, source_y, type_id_y]
Index: []

[0 rows x 33 columns]

In [87]:
#Just for faster calculation for details, dont run normally
# importing and creating df (has to have type_id)

# usage: specify file location, sample size and seed(used by random) 
#filepath = '/Users/Master/Documents/KU/2.Semester/Datascience/news_sample.csv' #
#s = 250                                            # desired sample size
#seed = 1                                           # seed used by Pseudorandom number generator

#df = pd.read_csv(filepath, index_col = [0])
#content = df['content']

In [14]:
import gensim 
from nltk.tokenize import sent_tokenize, word_tokenize
from gensim.models.doc2vec import TaggedDocument, Doc2Vec 
from gensim.utils import tokenize


In [14]:
#train

In [15]:
#train.set_index('id', inplace = True)
from sklearn.utils import shuffle
train = shuffle(train, random_state = 1)
test = shuffle(test, random_state = 1)
train.reset_index(inplace = True, drop = True)
test.reset_index(inplace = True, drop = True)

In [16]:
#this is how the tokenizer works
list(tokenize("This , is 5to TOKEN", lowercase = True))

['this', 'is', 'to', 'token']

In [18]:
%%time
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
series_content = train.content
#contTok = series_content.apply(nltk.word_tokenize)
typeLst = train.type_id.tolist()
#np.unique(typeLst, return_counts = True)

Wall time: 0 ns


In [19]:
test_content = test.content
test_typeLst = test.type_id.tolist()

In [549]:
#test_content
#test_typeLst

In [116]:
test_content

0        Mysterious metal spheres from space have lande...
1        Email this article\n\nManitoba Physicians Coll...
2        Why hospitals are a safe haven for hacking\n\n...
3        Addison Wiggin\n\nEvery month, JPMorgan Chase ...
4        LONDON - England - The lying fantasist and gol...
                               ...                        
12863    Put differently, they are nothing but snarky u...
12864    On the back of reports that the White Helmets ...
12865    Search by property\n\nA list of all pages that...
12866    The views expressed by the author do not neces...
12867    US Government Found GUILTY Of Murdering Martin...
Name: content, Length: 12868, dtype: object

In [14]:
#Try gensim tokenizer
testTok = test_content.apply(tokenize,lowercase =True)
for i in testTok.index:
    testTok[i] = list(testTok[i])

In [22]:
#Try gensim tokenizer
contTok = series_content.apply(tokenize,lowercase =True)
for i in contTok.index:
    contTok[i] = list(contTok[i])

In [ ]:
#Maybe fallback tokenizer
#contTok1 = series_content.apply(nltk.word_tokenize)

In [23]:
train.type[0]

'unreliable'

In [24]:
documents = [TaggedDocument(contTok, [i]) for i, contTok in enumerate(contTok)]
#contTok[291496]

In [28]:
#list(enumerate(contTok))[0]
#documents

In [25]:
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [180]:
model2 = Doc2Vec(documents, vector_size = 300, dm = 0, epochs=15, workers = 16)

020-06-10 14:06:06,299 : INFO : worker thread finished; awaiting finish of 3 more threads
2020-06-10 14:06:06,300 : INFO : worker thread finished; awaiting finish of 2 more threads
2020-06-10 14:06:06,300 : INFO : worker thread finished; awaiting finish of 1 more threads
2020-06-10 14:06:06,300 : INFO : worker thread finished; awaiting finish of 0 more threads
2020-06-10 14:06:06,301 : INFO : EPOCH - 9 : training on 33824106 raw words (26563430 effective words) took 14.6s, 1822045 effective words/s
2020-06-10 14:06:07,316 : INFO : EPOCH 10 - PROGRESS: at 6.65% examples, 1776201 words/s, in_qsize 32, out_qsize 0
2020-06-10 14:06:08,318 : INFO : EPOCH 10 - PROGRESS: at 13.51% examples, 1814294 words/s, in_qsize 29, out_qsize 1
2020-06-10 14:06:09,324 : INFO : EPOCH 10 - PROGRESS: at 20.55% examples, 1807446 words/s, in_qsize 31, out_qsize 0
2020-06-10 14:06:10,331 : INFO : EPOCH 10 - PROGRESS: at 27.66% examples, 1804961 words/s, in_qsize 32, out_qsize 2
2020-06-10 14:06:11,338 : INFO : 

In [181]:
%%time
model1 = Doc2Vec(documents, vector_size = , min_count = 3, window = 10, epochs=10, workers = 4)

SyntaxError: invalid syntax (<unknown>, line 1)

In [ ]:
#Eventuel træn andre modeller herefter:
#%%time
#model2 = Doc2Vec(documents, vector_size = 200, dm = 1, min_count = 3, window = 10, epochs= 10, workers = 4)

In [182]:
model2.most_similar('apple')

2020-06-10 14:07:58,329 : INFO : precomputing L2-norms of word weight vectors


[('inhabits', 0.23516283929347992),
 ('trio', 0.23322972655296326),
 ('су', 0.23255932331085205),
 ('rem', 0.2267533838748932),
 ('финансирование', 0.22597454488277435),
 ('seis', 0.22557631134986877),
 ('parigi', 0.2229282408952713),
 ('ciavarella', 0.21694324910640717),
 ('nita', 0.21591304242610931),
 ('obeying', 0.2151620239019394)]

In [31]:
model2.docvecs.count

51466

In [454]:
#documents[200]

In [58]:
tuple_list = model2.docvecs.most_similar(200)[:][0]

In [183]:
first_tuple_elements = [a_tuple[0] for a_tuple in tuple_list]
first_tuple_elements

IndexError: invalid index to scalar variable.

In [457]:
train.type.loc[train.type.index == 39974]

39974    fake
Name: type, dtype: object

In [319]:
#train.type.loc[train.index == 38424]

In [51]:
#See types of most similar documents for model2
#for idx in train.type.loc[train.type == 'fake'].index:
sim_labels1 = np.empty(10,dtype='object')
for i in range(len(sim_labels1)):
    sim_labels1[i] = train.type.loc[train.type.index == model2.docvecs.most_similar(16)[i][0]].values[0]

# amount of articles with given type equal to testing article
np.unique(sim_labels1,return_counts=True)

(array(['bias', 'conspiracy', 'fake'], dtype=object),
 array([8, 1, 1], dtype=int64))

In [36]:
#Lookup indeices for articles with certain types
train.type.loc[train.type == 'bias']

16       bias
21       bias
23       bias
34       bias
43       bias
         ... 
51398    bias
51399    bias
51400    bias
51416    bias
51464    bias
Name: type, Length: 5600, dtype: object

In [60]:
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import utils
from tqdm import tqdm
import multiprocessing


In [61]:
import numpy as np

In [62]:
#Model 1 traindata
train_arrays = np.zeros((model1.docvecs.count,150),dtype="float32")
train_labels = np.zeros(model1.docvecs.count,dtype="float32")
for i in range(model1.docvecs.count):
    train_arrays[i] = model1.docvecs[i]
    train_labels[i] = train.type_id[i]

NameError: name 'model1' is not defined

In [477]:
model2.docvecs.count

51466

In [185]:
#Model 2 traindata:
train_arrays2 = np.zeros((model2.docvecs.count,300),dtype="float32")
train_labels2 = np.zeros(model2.docvecs.count,dtype="float32")
for i in range(model2.docvecs.count):
    train_arrays2[i] = model2.docvecs[i]
    train_labels2[i] = train.type_id[i]

In [37]:
#np.unique(train_labels, return_counts = True)

In [538]:
#train_arrays[0]
#train_labels[0]
#model1.docvecs.most_similar([train_arrays[0]])
#train.loc[train.index == 37400]

In [64]:
#How infer_vector works:
token = "this is new sentence".split()
new_vector = model1.infer_vector(token)
sims = model1.docvecs.most_similar([new_vector])
#model2.docvecs.most_similar([new_vec])

NameError: name 'model1' is not defined

In [497]:
#new_vec = model2.infer_vector(contTok[2])

In [499]:
#model2.docvecs.most_similar([new_vec])

In [65]:
#Inferring vectors for testdata with model1
test_arrays = np.zeros((len(test),150),dtype = "float32")
for i in range(len(test)):
    test_arrays[i] = model1.infer_vector(testTok[i],steps = 15)   
test_labels = np.array(test_typeLst,dtype="float32")

#test_arrays = np.zeros((model1.docvecs.count,150),dtype="float32")
#test_labels = np.zeros(model1.docvecs.count,dtype="float32")

NameError: name 'model1' is not defined

In [186]:
%%time
#Inferring vectors for testdata with model2
test_arrays2 = np.zeros((len(test),300),dtype = "float32")
for i in range(len(test)):
    test_arrays2[i] = model2.infer_vector(testTok[i], epochs = 20, alpha = 0.025)   
test_labels = np.array(test_typeLst,dtype="float32")

Wall time: 3min 5s


In [146]:
#testTok[300]

In [149]:
#test_labels[300]

In [584]:
#np.unique(test_labels, return_counts=True)

In [187]:
model1.docvecs.most_similar([test_arrays[200]])

NameError: name 'model1' is not defined

In [188]:
test.type.loc[test.type.index == 3642]

3642    junksci
Name: type, dtype: object

In [189]:
#Find originalarticle types most similar to inferred vector by model1:
sim_labels = np.empty(10,dtype='object')
for i in range(len(sim_labels)):
    sim_labels[i] = train.type.loc[train.type.index == model1.docvecs.most_similar([test_arrays[10]])[i][0]].values[0]

np.unique(sim_labels,return_counts=True)

NameError: name 'model1' is not defined

In [190]:
model2.docvecs.most_similar([test_arrays2[200]])

2020-06-10 14:11:51,523 : INFO : precomputing L2-norms of doc weight vectors


[(10615, 0.5106222629547119),
 (35760, 0.500029444694519),
 (22072, 0.4754215180873871),
 (10282, 0.4753485321998596),
 (12222, 0.47503337264060974),
 (24140, 0.47311046719551086),
 (4678, 0.47090116143226624),
 (19009, 0.46703222393989563),
 (5028, 0.4660884439945221),
 (1725, 0.46571171283721924)]

In [192]:
train.type[10004]

'satire'

In [191]:
model2.docvecs.most_similar([test_arrays2[10]])

[(31820, 0.5368525981903076),
 (14004, 0.5289143323898315),
 (10004, 0.5062718391418457),
 (4258, 0.5002168416976929),
 (17200, 0.4998486638069153),
 (8084, 0.4979134798049927),
 (45557, 0.49462491273880005),
 (22523, 0.49202004075050354),
 (17669, 0.4897216856479645),
 (48858, 0.4863385558128357)]

In [193]:
#Find originalarticle types most similar to inferred vector by model2:
sim_labels = np.empty(10,dtype='object')
for i in range(len(sim_labels)):
    sim_labels[i] = train.type.loc[train.type.index == model2.docvecs.most_similar([test_arrays2[90]])[i][0]].values[0]

np.unique(sim_labels,return_counts=True)

(array(['clickbait', 'hate', 'political', 'reliable'], dtype=object),
 array([2, 2, 1, 5], dtype=int64))

In [194]:
#Get indices for testarticles of a certain type:
test.type.loc[test.type == 'reliable'].index

Int64Index([   11,    17,    25,    29,    54,    63,    75,    88,    90,
              124,
            ...
            12742, 12748, 12762, 12784, 12803, 12816, 12818, 12826, 12851,
            12866],
           dtype='int64', length=1045)

In [184]:
#model1.docvecs.most_similar([test_arrays[10]])

In [185]:
#train.type.loc[train.type == 'bias'].index

In [198]:
from sklearn.preprocessing import StandardScaler
#standardizing data
scaler = StandardScaler()
scaler.fit(train_arrays2)
X_train = scaler.transform(train_arrays2)
X_test = scaler.transform(test_arrays2)

In [78]:
len(train.loc[train.type == 'hate'])

2489

In [405]:
4000/2489
2489/400

1.6070711128967456

In [196]:
#Now train a logistic classifier:
#can try gridsearch for parameters:
#Logistic = LogisticRegression()
#grid = {"C" :np.logspace(0,4,10), "penalty": ["l1", "l2"]}
#logClf = GridSearchCV(Logistic, grid, cv = 5)
#best_model = logClf.fit(X_train, train_labels)
clfLog = LogisticRegression(C = 0.01,multi_class = 'multinomial', solver = 'saga', penalty = 'l2', warm_start = True)
clfLog.fit(X_train, train_labels2)

#classifier.fit(X_train,train_labels)
#classifier.n_iter_

LogisticRegression(C=0.01, multi_class='multinomial', solver='saga',
                   warm_start=True)

In [197]:
clfLog.score(X_test, test_labels)

0.6555020205160087

In [81]:
y_true = test_labels
#y_true
y_pred = clfLog.predict(X_test)

In [82]:
confusion_matrix(y_true,y_pred)

array([[ 674,   82,  147,   29,   87,   65,  193,   51,   54,   18],
       [ 104,  705,   62,   12,   26,   57,  175,   94,  152,   13],
       [ 133,   67,  810,   38,   51,   88,  101,   32,   68,   12],
       [  16,   18,   45, 1224,    6,   38,   32,    5,   14,    2],
       [  77,   48,   39,   18,  310,   19,   59,   25,   22,    6],
       [  27,   38,  107,   19,    4, 1107,   28,   24,   45,    1],
       [ 140,  159,  117,   20,   66,   36,  647,   93,  105,   17],
       [  70,   70,   21,   13,   17,   29,   56,  719,   43,    7],
       [  77,  108,   73,   16,   19,   53,   74,   23,  949,    8],
       [  28,   57,   26,    4,    9,   13,   26,   14,   29, 1194]],
      dtype=int64)

In [287]:
accuracy_score(y_true,y_pred)

0.6406526031383144

In [83]:
#Try GaussianNB:
from sklearn.naive_bayes import GaussianNB
clfNB = GaussianNB()
clfNB.fit(X_train, train_labels2)

GaussianNB()

In [84]:
clfNB.score(X_test,test_labels)

0.5508237488343177

In [252]:
from sklearn.svm import LinearSVC
LinSvm = LinearSVC()
LinSvm.fit(X_train, train_labels)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [85]:
LinSvm.score(X_test, test_labels)

NameError: name 'LinSvm' is not defined

In [86]:
#rbf kernel = 0 .72, poly kernel = 0.7
from sklearn import svm
from sklearn.model_selection import GridSearchCV
#parameters = {'C':[1,10], 'kernel': ('linear','rbf')}
clf = svm.SVC()
clf.fit(X_train,train_labels2)
#clf.score(X_test, y_test)

SVC()

In [87]:
clf.score(X_test,test_labels)

0.7239664283493938

In [199]:
y_pred_svm = clf.predict(X_test)

ValueError: X.shape[1] = 300 should be equal to 150, the number of features at training time

In [225]:
confusion_matrix(y_true,y_pred_svm)
#np.unique(train_labels2 == typeLst)

array([[603,  51,  73,  23,  50,  27, 106,  33,  34,   0],
       [101, 614,  37,  15,  13,  24,  97,  38,  61,   0],
       [117,  50, 578,  40,  34,  42,  98,   5,  34,   2],
       [ 17,  10,  25, 890,   5,  22,  19,   5,   7,   0],
       [ 81,  24,  31,  15, 382,   8,  54,  16,  11,   1],
       [ 31,  34,  45,  17,   5, 824,  12,   7,  24,   1],
       [173,  92,  72,  28,  27,  18, 501,  31,  57,   1],
       [ 42,  37,  13,   4,   8,   7,  33, 829,  27,   0],
       [ 58,  46,  25,  25,  11,  24,  41,  12, 755,   3],
       [ 21,  47,   8,   3,   6,   8,  21,   7,   9, 870]])

In [534]:
#Decicion tree
from sklearn import tree

treeClf = tree.DecisionTreeClassifier()
treeClf.fit(X_train, train_labels2)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [543]:
treeClf.score(X_test, test_labels)

0.2661641280696301

In [566]:
from sklearn.ensemble import RandomForestClassifier
forestClf = RandomForestClassifier()
forestClf.fit(X_train, train_labels2)

ValueError: Number of labels=38489 does not match number of samples=51466

In [542]:
forestClf.score(X_test, test_labels)

0.35708734846129936

In [203]:
from sklearn.neighbors import KNeighborsClassifier
KNN_clf = KNeighborsClassifier(n_neighbors=5)
KNN_clf.fit(X_train, train_labels2)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [207]:
KNN_clf.score(X_test, test_labels)

0.5564792684194119

In [605]:
np.unique(y_pred1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  9., 11.], dtype=float32)

In [593]:
confusion_matrix(y_true,y_pred1)

array([[252, 131, 121,  46, 244,  63, 101,  28,  12,   2],
       [ 27, 504,  69,  19,  99,  87, 103,  67,  23,   2],
       [ 54, 102, 408,  54, 186,  81,  79,  15,  21,   0],
       [ 30,  89, 150, 266, 181, 124,  92,  19,  44,   5],
       [ 11,  50,  63,  13, 422,  21,  25,  13,   5,   0],
       [  8,  55,  68,  20, 130, 691,  18,   8,   2,   0],
       [ 40, 186,  94,  38, 182,  46, 363,  32,  18,   1],
       [ 25,  79,  13,  10, 178,  54,  35, 591,  15,   0],
       [ 16, 119,  50,  67,  83,  63,  78,  43, 474,   7],
       [ 11,  46,  14,   9, 167,  15,  22,   6,   3, 707]])

In [389]:
#try tf-idf svm
from sklearn.feature_extraction.text import TfidfVectorizer
v = TfidfVectorizer()
x = v.fit_transform(train["content"])

In [609]:
# Setup scikit
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics import accuracy_score, log_loss
from sklearn.pipeline import Pipeline

# models
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier


# Naive Bayes
clf_NB = Pipeline([('vect', CountVectorizer()),
                   ('tfidf', TfidfTransformer()),
                   ('NB', MultinomialNB()),])
                   
# Support vector machine
clf_svm = Pipeline([('vect', CountVectorizer()),
                    ('tfidf', TfidfTransformer()),
                    ('svm', SGDClassifier()),])

In [644]:
clf_svm.fit(series_content,typeLst )

In [631]:
np.unique(test_labels == test_typeLst, return_counts = True)

(array([ True]), array([9623]))

In [646]:
clf_svm.score(test_content, test_labels)

0.7225397485191728

In [645]:
clf_svm.score(test_content, test_labels)clf_svm.score(test_content, test_labels)

SyntaxError: invalid syntax (<ipython-input-645-bc1c4179375a>, line 1)

In [585]:
#X_train
#len(train_labels2)

51466

In [589]:
train_labels2 = np.array(train_labels2)
len(train_labels2)

51466

In [581]:
#(X_train)
#len(train_labels2)

In [200]:
import tensorflow as tf

### Create Model size ###

# laver modellen
model = tf.keras.models.Sequential()
# tilføjer et input på modellen
model.add(tf.keras.layers.Flatten())

# relu er default aktiverings funktion. Lav den om hvis resultatet ikke er godt nok
model.add(tf.keras.layers.Dense(30, activation=tf.nn.relu))
# jeg tilføjer 2 lag til netwærket. Dette er fordi det er en simpel opgave
model.add(tf.keras.layers.Dense(30, activation=tf.nn.relu))
# jeg tilføjer 2 lag til netwærket. Dette er fordi det er en simpel opgave
model.add(tf.keras.layers.Dense(30, activation=tf.nn.relu))
# jeg tilføjer 2 lag til netwærket. Dette er fordi det er en simpel opgave
model.add(tf.keras.layers.Dense(30, activation=tf.nn.relu))
# jeg tilføjer 2 lag til netwærket. Dette er fordi det er en simpel opgave
model.add(tf.keras.layers.Dense(30, activation=tf.nn.relu))

#antallet (10) er antal output. Det er 10 tal i datasettet derfor skal der være et 10 tal
model.add(tf.keras.layers.Dense(20, activation=tf.nn.softmax))

# Dette er den mest komplexe del. adam er goto. Hvis der kun er 2 løsninger så brug binary_categorical_crossentropy eller binary_crossentropy i stedet for sparse_categorical_crossentropy
model.compile(optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'])

model.fit(X_train, train_labels2, epochs = 15)
# model.fit(X_train, train_labels2, batch_size=64, epochs = 15)

Epoch 1/15
1609/1609 [==============================] - 1s 670us/step - loss: 1.3161 - accuracy: 0.5580
Epoch 2/15
1609/1609 [==============================] - 1s 661us/step - loss: 0.9816 - accuracy: 0.6781
Epoch 3/15
1609/1609 [==============================] - 1s 651us/step - loss: 0.9090 - accuracy: 0.7023
Epoch 4/15
1609/1609 [==============================] - 1s 660us/step - loss: 0.8664 - accuracy: 0.7163
Epoch 5/15
1609/1609 [==============================] - 1s 670us/step - loss: 0.8406 - accuracy: 0.7250
Epoch 6/15
1609/1609 [==============================] - 1s 663us/step - loss: 0.8210 - accuracy: 0.7312
Epoch 7/15
1609/1609 [==============================] - 1s 659us/step - loss: 0.8061 - accuracy: 0.7354
Epoch 8/15
1609/1609 [==============================] - 1s 660us/step - loss: 0.7921 - accuracy: 0.7381
Epoch 9/15
1609/1609 [==============================] - 1s 661us/step - loss: 0.7795 - accuracy: 0.7436
Epoch 10/15
1609/1609 [==============================] - 1s 667u

In [202]:
val_loss, val_acc = model.evaluate(X_test,test_labels)
print(val_loss, val_acc)


403/403 [==============================] - 0s 484us/step - loss: 1.0131 - accuracy: 0.6864
1.013122797012329 0.6863537430763245


In [162]:
model.fit(X_train, train_labels2, batch_size=1, epochs = 3)

Epoch 1/3
51466/51466 [==============================] - 26s 496us/step - loss: 1.3845 - accuracy: 0.5289
Epoch 2/3
51466/51466 [==============================] - 25s 493us/step - loss: 1.2402 - accuracy: 0.5869
Epoch 3/3
51466/51466 [==============================] - 25s 495us/step - loss: 1.2241 - accuracy: 0.5912


In [101]:
from nltk.stem import PorterStemmer 
mySent = "These are my sentences in the books"
mySentTok = word_tokenize(mySent)
ps = PorterStemmer()
for w in mySentTok:
    mySentTok[w] = ps.stem(w)

TypeError: list indices must be integers or slices, not str